project:
  type: book

book:
  title: "Data Analysis in Business (First edition)"
  reader-mode: true
  cover-image: images/cover.png
  description: "A beginner guide to SQL, Power BI, data analysis, and data visualization."
  author: "Dr. Joan Tan"
  date: today
  chapters:
    - index.qmd

    - part: Course Overview
      chapters:
        - intro.qmd
        - team.qmd
        - schedule.qmd
    - part: Database Management System
      chapters:
        - dbms.qmd
        - sql_basics.qmd
        - sql_advanced.qmd
    - part: Data Analysis
      chapters:
        - introR.qmd
        - desc_stats.qmd
    - part: Communication and Story Telling
      chapters: 
        - powerbi.qmd


    - part: Data Visualization


    - part: Conclusion


#     # - summary.qmd
#     # - references.qmd
# 
# #bibliography: references.bib

format:
  html:
    theme: cosmo
    
webr: 
  show-startup-message: false     # Display status of webR initialization
  
filters:
  - webr

execute:
  freeze: true
