project:
  type: book

book:
  title: "Data Analysis in Business (First edition)"
  reader-mode: true
  cover-image: cover.png
  description: "A beginner guide to SQL, Power BI, data analysis, and data visualization."
  author: "Dr. Joan Tan"
  date: "4/29/2025"
  chapters:
    - index.qmd

    - part: Course Overview
      chapters:
        - intro.qmd
        - team.qmd
        - schedule.qmd
    - part: Database Management System
      chapters:
        - dbms.qmd
    - part: Power BI
      chapters:
        - powerbi.qmd
    - part: Data Analysis


    - part: Data Visualization


    - part: Conclusion


    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



